### ISSUE TITLE
Error when Compiling the final App

### ISSUE THREAD

**Issue by matiu** [phonegap/phonegap-plugin-barcodescanner#255]
Hi,

Using the current master version of the plugin & cordova 6.1.1 we get:

```
:compileReleaseJavaWithJavac/Users/ematiu/devel/copay/cordova/project/platforms/android/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:26: error: package com.google.zxing.client.android does not exist
import com.google.zxing.client.android.Intents;
                                      ^
/Users/ematiu/devel/copay/cordova/project/platforms/android/src/com/phonegap/plugins/barcodescanner/BarcodeScanner.java:173: error: package Intents does not exist
                        intentScan.putExtra(Intents.Scan.CAMERA_ID, obj.optBoolean(PREFER_FRONTCAMERA, false) ? 1 : 0);

```

when compiling the app.  Thanks a lot in advance!

**Comment by daserge** [comment]
@matiu, is this still actual?
I could not reproduce this locally.

**Comment by matiu** [comment]
Yes, we try in different notebook, all running OSX Lion.  Please let me know if there is anything we can do to try it further. Thanks!

**Comment by daserge** [comment]
The issue does not reproduce for me on OSX as well (tried on Yosemite 10.10.5).
Are you using crosswalk plugin?
Does the app build if you remove the barcodescanner?

**Comment by matiu** [comment]
Thanks for your response.

Yes. It builds OK with the fork we are using currently:
```
    cordova plugin add https://github.com/jrontend/phonegap-plugin-barcodescanner
```
the code of the app and the cordova script to build it  is at:
https://github.com/bitpay/copay/blob/master/cordova/build.sh#L87
(you can see there the other plugins we are using).

thanks a lot!

**Comment by daserge** [comment]
@matiu, that's strange as the JrontEnd' commit has been merged to master.
Are you sure you were testing with `the current master version`?
Could you try please again `cordova plugin add https://github.com/phonegap/phonegap-plugin-barcodescanner`?

**Comment by matthewgertner** [comment]
Did you have any luck tracking this down? I'm having exactly the same problem on PhoneGap Build using version 5.0.1 of the plugin from npm.

**Comment by matthewgertner** [comment]
Oops, never mind, I RTFM'd: https://github.com/phonegap/phonegap-plugin-barcodescanner#phonegap-build
